/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mondo_pizza26;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Ayesha
 */
public class DashBoard extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    public int OrderNumber;
    public String Order;


    /**
     * Creates new form DashBoard
     */
    public DashBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtOrderNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtOrder = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DashBoard");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 560));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Order Number:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        txtOrderNumber.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtOrderNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderNumberActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrderNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 230, 40));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" Item Ordered:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 190, -1));

        txtOrder.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 230, 40));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/cancel.png"))); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 100, 30));

        btnView.setBackground(new java.awt.Color(255, 255, 255));
        btnView.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/eye.png"))); // NOI18N
        btnView.setText("Display");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 100, 30));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/trash.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 90, 30));

        btnInsert.setBackground(new java.awt.Color(255, 255, 255));
        btnInsert.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnInsert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/insert.png"))); // NOI18N
        btnInsert.setText("Save");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel1.add(btnInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 90, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 0));

        tblData.setBackground(new java.awt.Color(102, 102, 102));
        tblData.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tblData.setForeground(new java.awt.Color(255, 255, 255));
        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Order"
            }
        ));
        tblData.setGridColor(new java.awt.Color(51, 51, 51));
        tblData.setSelectionForeground(new java.awt.Color(255, 153, 0));
        jScrollPane1.setViewportView(tblData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 570, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/place-order.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 215));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mondo_pizza26/top-view-fast-food-black-background-mock-up_23-2148321326_1_873x548.jpg"))); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(900, 500));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        
        
try{

            OrderNumber = Integer.parseInt(txtOrderNumber.getText());
            Order = txtOrder.getText();

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mondo-pizza26?zeroDateTimeBehavior=convertToNull","root","");
            stmt=con.createStatement();
            String query = "INSERT INTO `orders`(`Order Number`, `Order`) VALUES('"+OrderNumber+"','"+Order+"')";

            stmt.execute(query);
            JOptionPane.showMessageDialog(null, "Order Placed!!!" ,"Success" ,JOptionPane.INFORMATION_MESSAGE );

            txtOrderNumber.setText("");
            txtOrder.setText("");

        }catch (SQLException | ClassNotFoundException ex) {

            JOptionPane.showMessageDialog(null, "Exception"+ex ,"Error" ,JOptionPane.ERROR_MESSAGE );
        }

        
        
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel mdl = (DefaultTableModel)this.tblData.getModel();
        mdl.setRowCount(0);
        try{

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection ("jdbc:mysql://localhost:3306/mondo-pizza26?zeroDateTimeBehavior=convertToNull","root","");
            stmt=con.createStatement();
            String query = "Select * from `orders` ";
            stmt.execute(query);
            rs = stmt.getResultSet();

            while( rs.next() )
            {
                Object []row = { rs.getString("Order Number"),rs.getString("Order")};
                mdl.addRow(row);

            }
            this.tblData.setModel(mdl);

        }catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Failed:"+ex ,"Error" ,JOptionPane.ERROR_MESSAGE );
        }

        
        
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
       int DialogueResult = JOptionPane.showConfirmDialog(null, "Do You Really Want To Delete Order?","Confirmition",JOptionPane.YES_NO_OPTION );
        if(DialogueResult == JOptionPane.YES_OPTION)
        {
            try {
                DefaultTableModel mdl = (DefaultTableModel)this.tblData.getModel();
                int rowindex = this.tblData.getSelectedRow();
                String SpelerID = (String)this.tblData.getValueAt(rowindex,0);

 

                Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mondo-pizza26?zeroDateTimeBehavior=convertToNull","root","");
                stmt=con.createStatement();
                String query = " DELETE FROM `orders` WHERE `orders`.`Order Number` = '"+SpelerID+"' ";
                stmt.execute(query);
                mdl.removeRow(rowindex);
                JOptionPane.showMessageDialog(this, "Order Removed!" , "Deleted",JOptionPane.INFORMATION_MESSAGE);
            }
            catch (Exception w) {
                JOptionPane.showMessageDialog(this, "Please Select Order To Delete!" , "ALERT ", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtOrderNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderNumberActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtOrderNumber;
    // End of variables declaration//GEN-END:variables
}
